### PR TITLE
feat(ci): add status check for new workflow

### PR DESCRIPTION
**Pull request by aali309**
fixes: #283

### CODE REVIEW

**Comment by aali309** [comment]
pr [LINK]: (https://github.com/aali309/cryostat-core/pull/2)

image

image

**Comment by aali309** [comment]
@mwangggg its complaining about pulling the image when I test it locally?

**Comment by mwangggg** [comment]
ah it failed because an image hasn't been built for this specific ref for your PR.. perhaps the `CI build` workflow needs to be triggered on more PR events- I'll take a look

**Comment by mwangggg** [comment]
oh it's because you ran `/build_test` before the `CI build` workflow was completed- so those images hadn't been pushed to ghcr.io yet

**Comment by andrewazores** [comment]
I guess putting the workflows in the same concurrency group and using `cancel-in-progress: false` could be a useful queuing behaviour for that kind of case, but I don't know if there would be other downsides associated with that, and I haven't put any thought into what to use as the concurrency group ID to tie those things together - I guess it would just have to be the branch name/checkout ref?

**Comment by aali309** [comment]
> oh it's because you ran `/build_test` before the `CI build` workflow was completed- so those images hadn't been pushed to ghcr.io yet

yes, I figured after looking at the build again and I deleted the comment

**Comment by mwangggg** [comment]
Hmm if they're in the same concurrency group and the `/build_test` workflow is running, I guess whomever's PR it is will have to wait until it's done to push any changes - could cause an old image to be tested if they're not careful. But otherwise, I can't think of any other downsides.

**Comment by aali309** [comment]
> @andrewazores Hmm if they're in the same concurrency group and the `/build_test` workflow is running, I guess whomever's PR it is will have to wait until it's done to push any changes - could cause an old image to be tested if they're not careful. But otherwise, I can't think of any other downsides?

This is what I ran into at first.

**Comment by andrewazores** [comment]
Maybe there would be a way to group those things into a concurrency group based on the latest commit hash, so that when a new push comes in that has a new hash and is therefore in a new concurrency group/separate queue? I'm not sure if this is really worth the time investment to get working, it's going to come up pretty rarely and the workaround is just to wait for the initial build completion before invoking the build_test workflow.

**Comment by aali309** [comment]
> Maybe there would be a way to group those things into a concurrency group based on the latest commit hash, so that when a new push comes in that has a new hash and is therefore in a new concurrency group/separate queue? I'm not sure if this is really worth the time investment to get working, it's going to come up pretty rarely and the workaround is just to wait for the initial build completion before invoking the build_test workflow.

I agree about the time it might take to get this to work. May be something we can look at in the future?

**Comment by mwangggg** [comment]
we could add a step that checks if the image exists, and if not, exit with a message that informs the commenter to wait until the initial build and push is completed to try integration testing?

**Comment by aali309** [comment]
> we could add a step that checks if the image exists, and if not, exit with a message that informs the commenter to wait until the initial build and push is completed to try integration testing?

yes, this was what I was thinking as well.

**Comment by mwangggg** [comment]
> I guess putting the workflows in the same concurrency group and using `cancel-in-progress: false` could be a useful queuing behaviour for that kind of case, but I don't know if there would be other downsides associated with that, and I haven't put any thought into what to use as the concurrency group ID to tie those things together - I guess it would just have to be the branch name/checkout ref?

Also, I'm not sure if it's the best idea to have `cancel-in-progress: false` for these workflows. There could be lots of bot comments from relabelling etc. i.e.: https://github.com/cryostatio/cryostat-core/issues/281

**Comment by aali309** [comment]
Took a lot of time, to conclude with this one. Many other solutions available but they will require a lot of code change. May be later we can look to make it like `cryostat main` to adopt the  `retest` option?
image

**Comment by andrewazores** [comment]
Looks pretty good to me. Rebase please

**Pull request merged**
