### PR TITLE
chore(ci): restore CI on push workflow

### PR DESCRIPTION
**Pull request by mwangggg**
fixes: #277

### CODE REVIEW

**Comment by mwangggg** [comment]
not sure if I should update `setup-java` version to 21?

**Comment by andrewazores** [comment]
I was actually about to say the opposite. The published artifact builds with JDK 11 for wider compatibility: https://github.com/cryostatio/cryostat-core/blob/17a29a3daff78f69de36864817bd504a5c7b5473/.github/workflows/maven-publish.yaml#L26

so I think this should either match and build with 11 only, or it should be an 11/17/21 matrix.

**Comment by mwangggg** [comment]
I'll leave it as 11 then

**Comment by andrewazores** [comment]
I, uh, think that was a little excessive :sweat_smile: 

I suspect this is the problem: https://github.com/cryostatio/cryostat-core/blob/17a29a3daff78f69de36864817bd504a5c7b5473/.github/workflows/ci.yaml#L4

The concurrency group is based on the run ID, but each time the PR is relabelled or a new commit is pushed I think that triggers a new run with a new ID, so many concurrent jobs can be running in the background on the same actual code if we're just relabelling the PR etc.

**Comment by andrewazores** [comment]
Just to test that out ^

https://github.com/cryostatio/cryostat-core/actions/runs/6580357398

**Comment by andrewazores** [comment]
Nice, it passed - would be even nicer if the status got reported, either as a comment again like we already have elsewhere, or [as a status check item](https://josh-ops.com/posts/using-github-checks-api/)

**Review by andrewazores — APPROVED** [review]

**Pull request merged**
