### PR TITLE
chore(reports): remove HTML-based generation and transformers

### LINKED ISSUE #209: [Task] Update Automated Analysis `RuleEvaluation` with new JMC `IResult` fields
Update the `RuleEvaluation` to support the updated rule `IResult` fields: https://docs.oracle.com/en/java/java-components/jdk-mission-control/8/jmc-flightrecorder-rules/org/openjdk/jmc/flightrecorder/rules/IResult.html
 -core's `RuleEvaluation` object should probably be updated with `Explanation`, `Severity`, `Solution`, and `Summary` in multiple fields instead of 1 big description field in JMC 7. `suggestRecordingSettings` could also be looked into.

### LINKED ISSUE #246: Remove report transformer API
We've never used this and now that we have JSON reports format, which is the expected way forward, we will never use report transformers. They should be removed along with the JSoup dependency. Event templates services that use JSoup can use jdk.jfr.Configuration instead.

### PR DESCRIPTION
**Pull request by andrewazores**
- chore(reports): remove HTML-based generation and transformers
- restructure analysis result for separate fields
- remove JFR event types

Fixes #209
Fixes #246
Closes https://github.com/cryostatio/cryostat-reports/issues/14

### CODE REVIEW

**Comment by andrewazores** [comment]
This is part of a series of related PRs.

- [ ] https://github.com/cryostatio/cryostat-core/pull/261 this PR. Removes old code that produces HTML pre-formatted automated analysis reports. Also updates the JSON response format so that rather than the new `summary/explanation/description/suggestions` fields being pre-combined into the old-style `description` field, they are kept separate.
- [ ] https://github.com/cryostatio/cryostat/pull/1685 removes code that used the HTML pre-formatted reports format in favour of exclusively serving JSON reports. Technically breaks API, but the HTML reports were unlikely to be a useful format for any other consumer than our web-client to simply display inline.
- [ ] https://github.com/cryostatio/cryostat-reports/pull/137 same as above but for the reports sidecar
- [ ] https://github.com/cryostatio/cryostat-web/pull/1117 updates the Dashboard card implementation for Automated Analysis to use the new JSON format with separate `summary/explanation/description/suggestions`, and replaces the old `<ReportFrame/>` component that rendered the HTML reports with some reused components from the Dashboard card.

**Comment by andrewazores** [comment]
@aali309 @mwangggg ping

**Comment by andrewazores** [comment]
For ease of review:

```bash
$ CRYOSTAT_IMAGE=quay.io/andrewazores/cryostat:json-reports REPORTS_IMAGE=quay.io/andrewazores/cryostat-reports:json-reports sh smoketest.sh
```

**Review by mwangggg — APPROVED** [review]
LGTM :+1:

**Review by aali309 — APPROVED** [review]
Everything looks good to me as well

**Pull request merged**
