### PR TITLE
feat(jvmid): provide method for determining JVM's own hash ID without JMX connection

### PR DESCRIPTION
**Pull request by andrewazores**
Related to https://github.com/cryostatio/cryostat-agent/issues/278

### CODE REVIEW

**Comment by mwangggg** [comment]
I don't really understand why this error is occurring... I opened a PR in my forked repo and it's able to pull the image

**Comment by andrewazores** [comment]
I'm not sure either. It's complaining about being "denied", and I can see that the image it tried to pull does actually exist in the container image registry associated with this repository, so I guessed it had to do with the Actions default permissions level change - but that still doesn't sound right, because the change was just from granting read+write to read-only permissions by default. And I would expect that the action being denied only needs permission to read the container image.

**Comment by aali309** [comment]
> I'm not sure either. It's complaining about being "denied", and I can see that the image it tried to pull does actually exist in the container image registry associated with this repository, so I guessed it had to do with the Actions default permissions level change - but that still doesn't sound right, because the change was just from granting read+write to read-only permissions by default. And I would expect that the action being denied only needs permission to read the container image.

may be adding : `permissions: write` after logging in?
``` - name: ghcr login
      uses: redhat-actions/podman-login@v1
      with:
        registry: ghcr.io/${{ github.repository_owner }}
        username: ${{ github.event.comment.user.login }}
        password: ${{ secrets.GITHUB_TOKEN }} 
        permissions: write
        ```

**Comment by mwangggg** [comment]
> > I'm not sure either. It's complaining about being "denied", and I can see that the image it tried to pull does actually exist in the container image registry associated with this repository, so I guessed it had to do with the Actions default permissions level change - but that still doesn't sound right, because the change was just from granting read+write to read-only permissions by default. And I would expect that the action being denied only needs permission to read the container image.
> 
> may be adding : `permissions: read` after logging in?
> 
> ```
>       uses: redhat-actions/podman-login@v1
>       with:
>         registry: ghcr.io/${{ github.repository_owner }}
>         username: ${{ github.event.comment.user.login }}
>         password: ${{ secrets.GITHUB_TOKEN }} 
>         permissions: read
>         ```
> the current setup looks right though and works well on my local branch too.
> ```

I'm pretty sure the `redhat-actions/podman-login@v1` doesn't have a permissions input: https://github.com/redhat-actions/podman-login#action-inputs

**Comment by aali309** [comment]
> > > I'm not sure either. It's complaining about being "denied", and I can see that the image it tried to pull does actually exist in the container image registry associated with this repository, so I guessed it had to do with the Actions default permissions level change - but that still doesn't sound right, because the change was just from granting read+write to read-only permissions by default. And I would expect that the action being denied only needs permission to read the container image.
> 
> > 
> 
> > may be adding : `permissions: read` after logging in?
> 
> > 
> 
> > ```
> 
> >       uses: redhat-actions/podman-login@v1
> 
> >       with:
> 
> >         registry: ghcr.io/${{ github.repository_owner }}
> 
> >         username: ${{ github.event.comment.user.login }}
> 
> >         password: ${{ secrets.GITHUB_TOKEN }} 
> 
> >         permissions: read
> 
> >         ```
> 
> > the current setup looks right though and works well on my local branch too.
> 
> > ```
> 
> 
> 
> I'm pretty sure the `redhat-actions/podman-login@v1` doesn't have a permissions input: https://github.com/redhat-actions/podman-login#action-inputs

Yes, it doesn't, the current setup look right

**Comment by mwangggg** [comment]
> I'm not sure either. It's complaining about being "denied", and I can see that the image it tried to pull does actually exist in the container image registry associated with this repository, so I guessed it had to do with the Actions default permissions level change - but that still doesn't sound right, because the change was just from granting read+write to read-only permissions by default. And I would expect that the action being denied only needs permission to read the container image.

Oh I see what the problem is. https://github.com/cryostatio/cryostat-core/actions/runs/7063961328/job/19231025484#step:1:16 For some reason, only Metadata has read permissions. I'm not sure what happened here, considering the organizational permisisons changes should still provide contents and packages read-only permissions. But explicitly adding the `packages: read` permissions should fix this error for now until I figure out exactly why they're missing :smile:

**Comment by aali309** [comment]
> LGTM

Just rebase, please.

**Comment by mwangggg** [comment]
oh I'm glad adding the permission worked!!

**Comment by mwangggg** [comment]
> Any other review thoughts @mwangggg or can I merge this?

Looks good to me too :+1:

**Pull request merged**
