### PR TITLE
chore(jmc-core): Upgrade Java Mission Control to version 8.1.0

### LINKED ISSUE #95: [Task] Update to JMC 8
JMC 8 (8.0.1 now) is released and available on Maven Central:

https://search.maven.org/search?q=org.openjdk.jmc

### PR DESCRIPTION
**Pull request by oscerd**
Fixes #95 

Pointing JMC 8.1.0

### CODE REVIEW

**Comment by oscerd** [comment]
cc @andrewazores

**Comment by andrewazores** [comment]
This will take some more attention to review. I will need to test the main Cryostat project with this upgraded version and ensure everything still works as expected after the major JMC version bump.

**Comment by aptmac** [comment]
Just a heads up on this, `JfrHtmlRulesReport` (used to generate the automated analysis in `ReportGenerator`) is broken as of JMC 8; I would give this a test to make sure the automated analysis pages can be generated.

The upstream issue can be tracked at: https://bugs.openjdk.java.net/browse/JMC-7231 [[0]](https://bugs.openjdk.java.net/browse/JMC-7231)

There is currently a fix under review [[1]](https://github.com/openjdk/jmc/pull/302), but currently requires a bit more work. A fix will hopefully be incorporated in 8.2.0.

[0] https://bugs.openjdk.java.net/browse/JMC-7231
[1] https://github.com/openjdk/jmc/pull/302

**Comment by oscerd** [comment]
Do you need any help on this?

**Comment by andrewazores** [comment]
I haven't had a chance to test this, although now that I'm here thinking about this again I think upgrading the JMC version will take a little more work. For downstream build purposes we have some portions of JMC forked and embedded directly into our -core here ( https://github.com/cryostatio/cryostat-core/tree/main/src/main/java/org/openjdk/jmc ). So, not only does the pom need to be updated for the new JMC version, but these embedded sources need to be either removed or updated as well. @ebaron - what's your take?

**Comment by ebaron** [comment]
There's some work happening upstream in JMC to move remote JMX utilities to JMC Core: https://bugs.openjdk.java.net/browse/JMC-7069. The embedded sources in this project are a temporary measure to avoid pulling in Eclipse dependencies until this refactoring is done and we no longer need to depend on the JMC Application code.

Updating the embedded JMC application sources in this project is a time consuming and error prone process, but it may be worth doing. I expect that we would want to keep both the JMC core dependency and embedded JMC application sources at the same version.

**Comment by oscerd** [comment]
@jiekang sure, I'll update once it will be available.

**Comment by oscerd** [comment]
8.2.0 is out. Is it a target for Cryostat-core?

**Comment by andrewazores** [comment]
@oscerd yes, we just had our planning meeting for the next Cryostat release and updating cryostat-core for JMC 8.1.1 or 8.2.0 is a higher priority item on the list. It does not seem that the JMC refactoring to extract all of the parts we use into jmc-core is done yet, so there is still a need to manually update the embedded fork within cryostat-core as well.

**Comment by andrewazores** [comment]
Superseded by #201

**Pull request closed without merging**
